var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/booking/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__017-w_m._.js")
R.c("server/chunks/ssr/0sos_next_dist_0k.7_tc._.js")
R.c("server/chunks/ssr/0sos_next_dist_esm_build_templates_app-page_071.~.2.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n6jx65._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mftzia._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p31yv3._.js")
R.c("server/chunks/ssr/goldenhive-frontend_0gapa6.._.js")
R.c("server/chunks/ssr/0sos_next_dist_0p-jsbo._.js")
R.c("server/chunks/ssr/goldenhive-frontend_0~s1br0._.js")
R.c("server/chunks/ssr/goldenhive-frontend_src_0sx84f1._.js")
R.c("server/chunks/ssr/0sos_next_dist_client_components_0xp4up0._.js")
R.c("server/chunks/ssr/0sos_next_dist_client_components_builtin_forbidden_0r2sh-m.js")
R.c("server/chunks/ssr/0sos_next_dist_client_components_builtin_unauthorized_0jp9rlg.js")
R.c("server/chunks/ssr/0sos_next_dist_client_components_builtin_global-error_0qt8to..js")
R.c("server/chunks/ssr/goldenhive-frontend_0hw5ozu._.js")
R.m(83714)
module.exports=R.m(83714).exports
