export const countries = [
  {"name": "Afghanistan", "flag": "🇦🇫", "code": "AF", "dial_code": "+93"},
  {"name": "Albania", "flag": "🇦🇱", "code": "AL", "dial_code": "+355"},
  {"name": "Algeria", "flag": "🇩🇿", "code": "DZ", "dial_code": "+213"},
  {"name": "Andorra", "flag": "🇦🇩", "code": "AD", "dial_code": "+376"},
  {"name": "Angola", "flag": "🇦🇴", "code": "AO", "dial_code": "+244"},
  {"name": "Argentina", "flag": "🇦🇷", "code": "AR", "dial_code": "+54"},
  {"name": "Armenia", "flag": "🇦🇲", "code": "AM", "dial_code": "+374"},
  {"name": "Australia", "flag": "🇦🇺", "code": "AU", "dial_code": "+61"},
  {"name": "Austria", "flag": "🇦🇹", "code": "AT", "dial_code": "+43"},
  {"name": "Azerbaijan", "flag": "🇦🇿", "code": "AZ", "dial_code": "+994"},
  {"name": "Bahamas", "flag": "🇧🇸", "code": "BS", "dial_code": "+1242"},
  {"name": "Bahrain", "flag": "🇧🇭", "code": "BH", "dial_code": "+973"},
  {"name": "Bangladesh", "flag": "🇧🇩", "code": "BD", "dial_code": "+880"},
  {"name": "Belarus", "flag": "🇧🇾", "code": "BY", "dial_code": "+375"},
  {"name": "Belgium", "flag": "🇧🇪", "code": "BE", "dial_code": "+32"},
  {"name": "Belize", "flag": "🇧🇿", "code": "BZ", "dial_code": "+501"},
  {"name": "Benin", "flag": "🇧🇯", "code": "BJ", "dial_code": "+229"},
  {"name": "Bhutan", "flag": "🇧🇹", "code": "BT", "dial_code": "+975"},
  {"name": "Bolivia", "flag": "🇧🇴", "code": "BO", "dial_code": "+591"},
  {"name": "Bosnia and Herzegovina", "flag": "🇧🇦", "code": "BA", "dial_code": "+387"},
  {"name": "Botswana", "flag": "🇧🇼", "code": "BW", "dial_code": "+267"},
  {"name": "Brazil", "flag": "🇧🇷", "code": "BR", "dial_code": "+55"},
  {"name": "Brunei", "flag": "🇧🇳", "code": "BN", "dial_code": "+673"},
  {"name": "Bulgaria", "flag": "🇧🇬", "code": "BG", "dial_code": "+359"},
  {"name": "Burkina Faso", "flag": "🇧🇫", "code": "BF", "dial_code": "+226"},
  {"name": "Burundi", "flag": "🇧🇮", "code": "BI", "dial_code": "+257"},
  {"name": "Cambodia", "flag": "🇰🇭", "code": "KH", "dial_code": "+855"},
  {"name": "Cameroon", "flag": "🇨🇲", "code": "CM", "dial_code": "+237"},
  {"name": "Canada", "flag": "🇨🇦", "code": "CA", "dial_code": "+1"},
  {"name": "Chad", "flag": "🇹🇩", "code": "TD", "dial_code": "+235"},
  {"name": "Chile", "flag": "🇨🇱", "code": "CL", "dial_code": "+56"},
  {"name": "China", "flag": "🇨🇳", "code": "CN", "dial_code": "+86"},
  {"name": "Colombia", "flag": "🇨🇴", "code": "CO", "dial_code": "+57"},
  {"name": "Comoros", "flag": "🇰🇲", "code": "KM", "dial_code": "+269"},
  {"name": "Congo", "flag": "🇨🇬", "code": "CG", "dial_code": "+242"},
  {"name": "Costa Rica", "flag": "🇨🇷", "code": "CR", "dial_code": "+506"},
  {"name": "Croatia", "flag": "🇭🇷", "code": "HR", "dial_code": "+385"},
  {"name": "Cuba", "flag": "🇨🇺", "code": "CU", "dial_code": "+53"},
  {"name": "Cyprus", "flag": "🇨🇾", "code": "CY", "dial_code": "+357"},
  {"name": "Czech Republic", "flag": "🇨🇿", "code": "CZ", "dial_code": "+420"},
  {"name": "Denmark", "flag": "🇩🇰", "code": "DK", "dial_code": "+45"},
  {"name": "Djibouti", "flag": "🇩🇯", "code": "DJ", "dial_code": "+253"},
  {"name": "Ecuador", "flag": "🇪🇨", "code": "EC", "dial_code": "+593"},
  {"name": "Egypt", "flag": "🇪🇬", "code": "EG", "dial_code": "+20"},
  {"name": "El Salvador", "flag": "🇸🇻", "code": "SV", "dial_code": "+503"},
  {"name": "Estonia", "flag": "🇪🇪", "code": "EE", "dial_code": "+372"},
  {"name": "Ethiopia", "flag": "🇪🇹", "code": "ET", "dial_code": "+251"},
  {"name": "Fiji", "flag": "🇫🇯", "code": "FJ", "dial_code": "+679"},
  {"name": "Finland", "flag": "🇫🇮", "code": "FI", "dial_code": "+358"},
  {"name": "France", "flag": "🇫🇷", "code": "FR", "dial_code": "+33"},
  {"name": "Gabon", "flag": "🇬🇦", "code": "GA", "dial_code": "+241"},
  {"name": "Gambia", "flag": "🇬🇲", "code": "GM", "dial_code": "+220"},
  {"name": "Georgia", "flag": "🇬🇪", "code": "GE", "dial_code": "+995"},
  {"name": "Germany", "flag": "🇩🇪", "code": "DE", "dial_code": "+49"},
  {"name": "Ghana", "flag": "🇬🇭", "code": "GH", "dial_code": "+233"},
  {"name": "Greece", "flag": "🇬🇷", "code": "GR", "dial_code": "+30"},
  {"name": "Guatemala", "flag": "🇬🇹", "code": "GT", "dial_code": "+502"},
  {"name": "Guinea", "flag": "🇬🇳", "code": "GN", "dial_code": "+224"},
  {"name": "Haiti", "flag": "🇭🇹", "code": "HT", "dial_code": "+509"},
  {"name": "Honduras", "flag": "🇭🇳", "code": "HN", "dial_code": "+504"},
  {"name": "Hungary", "flag": "🇭🇺", "code": "HU", "dial_code": "+36"},
  {"name": "Iceland", "flag": "🇮🇸", "code": "IS", "dial_code": "+354"},
  {"name": "India", "flag": "🇮🇳", "code": "IN", "dial_code": "+91"},
  {"name": "Indonesia", "flag": "🇮🇩", "code": "ID", "dial_code": "+62"},
  {"name": "Iran", "flag": "🇮🇷", "code": "IR", "dial_code": "+98"},
  {"name": "Iraq", "flag": "🇮🇶", "code": "IQ", "dial_code": "+964"},
  {"name": "Ireland", "flag": "🇮🇪", "code": "IE", "dial_code": "+353"},
  {"name": "Israel", "flag": "🇮🇱", "code": "IL", "dial_code": "+972"},
  {"name": "Italy", "flag": "🇮🇹", "code": "IT", "dial_code": "+39"},
  {"name": "Jamaica", "flag": "🇯🇲", "code": "JM", "dial_code": "+1876"},
  {"name": "Japan", "flag": "🇯🇵", "code": "JP", "dial_code": "+81"},
  {"name": "Jordan", "flag": "🇯🇴", "code": "JO", "dial_code": "+962"},
  {"name": "Kazakhstan", "flag": "🇰🇿", "code": "KZ", "dial_code": "+7"},
  {"name": "Kenya", "flag": "🇰🇪", "code": "KE", "dial_code": "+254"},
  {"name": "Kuwait", "flag": "🇰🇼", "code": "KW", "dial_code": "+965"},
  {"name": "Kyrgyzstan", "flag": "🇰🇬", "code": "KG", "dial_code": "+996"},
  {"name": "Laos", "flag": "🇱🇦", "code": "LA", "dial_code": "+856"},
  {"name": "Latvia", "flag": "🇱🇻", "code": "LV", "dial_code": "+371"},
  {"name": "Lebanon", "flag": "🇱🇧", "code": "LB", "dial_code": "+961"},
  {"name": "Liberia", "flag": "🇱🇷", "code": "LR", "dial_code": "+231"},
  {"name": "Libya", "flag": "🇱🇾", "code": "LY", "dial_code": "+218"},
  {"name": "Lithuania", "flag": "🇱🇹", "code": "LT", "dial_code": "+370"},
  {"name": "Luxembourg", "flag": "🇱🇺", "code": "LU", "dial_code": "+352"},
  {"name": "Madagascar", "flag": "🇲🇬", "code": "MG", "dial_code": "+261"},
  {"name": "Malawi", "flag": "🇲🇼", "code": "MW", "dial_code": "+265"},
  {"name": "Malaysia", "flag": "🇲🇾", "code": "MY", "dial_code": "+60"},
  {"name": "Maldives", "flag": "🇲🇻", "code": "MV", "dial_code": "+960"},
  {"name": "Mali", "flag": "🇲🇱", "code": "ML", "dial_code": "+223"},
  {"name": "Malta", "flag": "🇲🇹", "code": "MT", "dial_code": "+356"},
  {"name": "Mauritania", "flag": "🇲🇷", "code": "MR", "dial_code": "+222"},
  {"name": "Mauritius", "flag": "🇲🇺", "code": "MU", "dial_code": "+230"},
  {"name": "Mexico", "flag": "🇲🇽", "code": "MX", "dial_code": "+52"},
  {"name": "Moldova", "flag": "🇲🇩", "code": "MD", "dial_code": "+373"},
  {"name": "Monaco", "flag": "🇲🇨", "code": "MC", "dial_code": "+377"},
  {"name": "Mongolia", "flag": "🇲🇳", "code": "MN", "dial_code": "+976"},
  {"name": "Montenegro", "flag": "🇲🇪", "code": "ME", "dial_code": "+382"},
  {"name": "Morocco", "flag": "🇲🇦", "code": "MA", "dial_code": "+212"},
  {"name": "Mozambique", "flag": "🇲🇿", "code": "MZ", "dial_code": "+258"},
  {"name": "Myanmar", "flag": "🇲🇲", "code": "MM", "dial_code": "+95"},
  {"name": "Namibia", "flag": "🇳🇦", "code": "NA", "dial_code": "+264"},
  {"name": "Nepal", "flag": "🇳🇵", "code": "NP", "dial_code": "+977"},
  {"name": "Netherlands", "flag": "🇳🇱", "code": "NL", "dial_code": "+31"},
  {"name": "New Zealand", "flag": "🇳🇿", "code": "NZ", "dial_code": "+64"},
  {"name": "Nicaragua", "flag": "🇳🇮", "code": "NI", "dial_code": "+505"},
  {"name": "Niger", "flag": "🇳🇪", "code": "NE", "dial_code": "+227"},
  {"name": "Nigeria", "flag": "🇳🇬", "code": "NG", "dial_code": "+234"},
  {"name": "North Korea", "flag": "🇰🇵", "code": "KP", "dial_code": "+850"},
  {"name": "Norway", "flag": "🇳🇴", "code": "NO", "dial_code": "+47"},
  {"name": "Oman", "flag": "🇴🇲", "code": "OM", "dial_code": "+968"},
  {"name": "Pakistan", "flag": "🇵🇰", "code": "PK", "dial_code": "+92"},
  {"name": "Panama", "flag": "🇵🇦", "code": "PA", "dial_code": "+507"},
  {"name": "Papua New Guinea", "flag": "🇵🇬", "code": "PG", "dial_code": "+675"},
  {"name": "Paraguay", "flag": "🇵🇾", "code": "PY", "dial_code": "+595"},
  {"name": "Peru", "flag": "🇵🇪", "code": "PE", "dial_code": "+51"},
  {"name": "Philippines", "flag": "🇵🇭", "code": "PH", "dial_code": "+63"},
  {"name": "Poland", "flag": "🇵🇱", "code": "PL", "dial_code": "+48"},
  {"name": "Portugal", "flag": "🇵🇹", "code": "PT", "dial_code": "+351"},
  {"name": "Qatar", "flag": "🇶🇦", "code": "QA", "dial_code": "+974"},
  {"name": "Romania", "flag": "🇷🇴", "code": "RO", "dial_code": "+40"},
  {"name": "Russia", "flag": "🇷🇺", "code": "RU", "dial_code": "+7"},
  {"name": "Rwanda", "flag": "🇷🇼", "code": "RW", "dial_code": "+250"},
  {"name": "Saudi Arabia", "flag": "🇸🇦", "code": "SA", "dial_code": "+966"},
  {"name": "Senegal", "flag": "🇸🇳", "code": "SN", "dial_code": "+221"},
  {"name": "Serbia", "flag": "🇷🇸", "code": "RS", "dial_code": "+381"},
  {"name": "Singapore", "flag": "🇸🇬", "code": "SG", "dial_code": "+65"},
  {"name": "Slovakia", "flag": "🇸🇰", "code": "SK", "dial_code": "+421"},
  {"name": "Slovenia", "flag": "🇸🇮", "code": "SI", "dial_code": "+386"},
  {"name": "Somalia", "flag": "🇸🇴", "code": "SO", "dial_code": "+252"},
  {"name": "South Africa", "flag": "🇿🇦", "code": "ZA", "dial_code": "+27"},
  {"name": "South Korea", "flag": "🇰🇷", "code": "KR", "dial_code": "+82"},
  {"name": "Spain", "flag": "🇪🇸", "code": "ES", "dial_code": "+34"},
  {"name": "Sri Lanka", "flag": "🇱🇰", "code": "LK", "dial_code": "+94"},
  {"name": "Sudan", "flag": "🇸🇩", "code": "SD", "dial_code": "+249"},
  {"name": "Sweden", "flag": "🇸🇪", "code": "SE", "dial_code": "+46"},
  {"name": "Switzerland", "flag": "🇨🇭", "code": "CH", "dial_code": "+41"},
  {"name": "Syria", "flag": "🇸🇾", "code": "SY", "dial_code": "+963"},
  {"name": "Taiwan", "flag": "🇹🇼", "code": "TW", "dial_code": "+886"},
  {"name": "Tajikistan", "flag": "🇹🇯", "code": "TJ", "dial_code": "+992"},
  {"name": "Tanzania", "flag": "🇹🇿", "code": "TZ", "dial_code": "+255"},
  {"name": "Thailand", "flag": "🇹🇭", "code": "TH", "dial_code": "+66"},
  {"name": "Tunisia", "flag": "🇹🇳", "code": "TN", "dial_code": "+216"},
  {"name": "Turkey", "flag": "🇹🇷", "code": "TR", "dial_code": "+90"},
  {"name": "Turkmenistan", "flag": "🇹🇲", "code": "TM", "dial_code": "+993"},
  {"name": "Uganda", "flag": "🇺🇬", "code": "UG", "dial_code": "+256"},
  {"name": "Ukraine", "flag": "🇺🇦", "code": "UA", "dial_code": "+380"},
  {"name": "United Arab Emirates", "flag": "🇦🇪", "code": "AE", "dial_code": "+971"},
  {"name": "United Kingdom", "flag": "🇬🇧", "code": "GB", "dial_code": "+44"},
  {"name": "United States", "flag": "🇺🇸", "code": "US", "dial_code": "+1"},
  {"name": "Uruguay", "flag": "🇺🇾", "code": "UY", "dial_code": "+598"},
  {"name": "Uzbekistan", "flag": "🇺🇿", "code": "UZ", "dial_code": "+998"},
  {"name": "Venezuela", "flag": "🇻🇪", "code": "VE", "dial_code": "+58"},
  {"name": "Vietnam", "flag": "🇻🇳", "code": "VN", "dial_code": "+84"},
  {"name": "Yemen", "flag": "🇾🇪", "code": "YE", "dial_code": "+967"},
  {"name": "Zambia", "flag": "🇿🇲", "code": "ZM", "dial_code": "+260"},
  {"name": "Zimbabwe", "flag": "🇿🇼", "code": "ZW", "dial_code": "+263"}
];
